pimcore/customer-data-framework

src/Newsletter/Queue/DefaultNewsletterQueue.php
src/Newsletter/Queue/NewsletterQueueInterface.php

fixes customer object creation error.

fix typecast in enqueueCustomer method

---

src/CustomerView/Customer/Maintenance.php
src/Resources/config/services.yml

Extracted from #48 (without code style fixes).

Maintenance job to clean up unused temporary customers

---

composer.json
frontend-samples/sso_client/src/AppBundle/Resources/config/pimcore/security.yml
src/Controller/Admin/Customers/FilterDefinitionController.php
src/Controller/Admin/CustomersController.php
src/Controller/Admin/GDPRDataController.php
src/Controller/Admin/HelperController.php
src/Controller/Admin/RulesController.php
src/Controller/Admin/SegmentAssignmentController.php
src/Controller/Admin/TemplatesController.php
src/Controller/Report/TermSegmentBuilderController.php
src/Resources/config/services.yml

Reflect changes to admin controllers and fix Symfony 3.4 specific deprecations.

Pimcore 5.1 Support

---

src/CustomerSaveManager/DefaultCustomerSaveManager.php

Reverts pimcore/customer-data-framework#61

Revert "skip duplicates check if the customer is inactive"

---

src/Newsletter/ProviderHandler/Mailchimp/TemplateExporter.php

Prevent MailChimp merge tags from being absolutized when used in href

---

src/Controller/Admin.php

Currently only a single entry is shown on each page of the customer listing. That bug was introduced in #108.

Fix CustomersController:listAction defaultPageSize

---

src/Resources/public/js/startup.js

Resolves #115
Oriented to documentation: https://pimcore.com/docs/6.x/Development_Documentation/Extending_Pimcore/Bundle_Developers_Guide/Plugin_Backend_UI.html#page_Adding-Custom-Main-Navigation-Items

Fix Toolbar: Mouseover doesn't work

---

src/Templating/Helper/JsConfig.php

Update JsConfig.php - BugFix for __toString()

---

src/Newsletter/ProviderHandler/Mailchimp.php
src/Newsletter/ProviderHandler/Mailchimp/CustomerExporter/SingleExporter.php

Some additional helper methods for custom integrations:
- fetchCustomer
- subscribeCustomerPending
- subscribeCustomerWithStatus

Add additional methods to Mailchimp newsletter handler

---

src/Newsletter/ProviderHandler/Mailchimp.php

[Mailchimp Sync] fix subscribe with status method

---

src/Controller/Admin/GDPRDataController.php
src/Controller/Rest/Api/DeletionsController.php
src/Controller/Rest/Api/SegmentsOfCustomersController.php
src/Controller/Rest/CrudHandlerController.php
src/Controller/Rest/Mailchimp/WebhookController.php
src/Controller/Rest/Newsletter/AdminController.php

[Routing] Change routing annotations to core Symfony

---

src/DependencyInjection/Configuration.php

Fix:  Undefined index: duplicates_view

---

src/Resources/config/services.yml

Fix installer warnings

---

src/Event/Newsletter/Mailchimp/TemplateExportResolveProviderHandlerEvent.php

since prividerHandler can be null this will throw an exception in case of null

removed return value declaration from getProviderHandler

---

install/class_source/class_CustomerSegmentGroup_export.json
install/class_source/class_CustomerSegment_export.json
install/class_source/class_LinkActivityDefinition_export.json
install/class_source/class_SsoIdentity_export.json
install/class_source/class_TermSegmentBuilderDefinition_export.json
install/class_source/optional/class_Customer_export.json

[Models] Add type hints to customer interfaces

---

src/ActivityStore/MariaDb.php
src/ActivityStore/SqlActivityStore.php

[Activities] Restore activity meta-data storage

---

src/Model/CustomerView/FilterDefinition/Dao.php
src/Model/CustomerView/FilterDefinition/Listing/Dao.php
src/SegmentAssignment/Indexer/Indexer.php
src/SegmentAssignment/QueueBuilder/DefaultQueueBuilder.php
src/SegmentAssignment/SegmentAssigner/SegmentAssigner.php

Support for Primary-Replica Db connection

---

src/Model/ActivityList/DefaultMariaDbActivityList/MariaDbDao.php
src/Model/ActivityList/DefaultMariaDbActivityList/MySqlDao.php
src/Model/ActivityStoreEntry/DefaultActivityStoreEntry.php
src/Service/MariaDb.php
tests/Model/Activity/ActivityTest.php

fixes
- set conditions with params to activity listing
- tracking activity with empty attributes (in maria db)

[Activity Store] Bugfixing

---

doc/02_Installation/01_Update.md
src/GDPR/DataProvider/Customers.php
src/Model/AbstractObjectActivity.php
src/Service/ObjectToArray.php

[Pimcore X] Make GDPR Exporter independent from REST Webservices

---

composer.json
src/CustomerList/Exporter/Xlsx.php

Upgrade box/spout Version

---

src/CustomerSaveManager/DefaultCustomerSaveManager.php

Validate after applying save handlers
