src/Resources/config/services.yml
src/Resources/config/services_security.yml
src/Resources/config/services_security_oauth_client.yml

Adds alias definitions for interfaces to fix autowiring warnings as `User Deprecated: Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "cmf.encryption_service" service to "CustomerManagementFrameworkBundle\Encryption\EncryptionServiceInterface" instead.` and adds explicit wiring for arguments which trigger autowiring warnings.

Update service config to fix autowiring deprecations

---

src/Model/AbstractCustomer/DefaultAbstractUserawareCustomer.php
src/Model/Traits/DefaultUserawareCustomerTrait.php

regarding #25 it would also be nice to move the default useraware customer functionality to a trait since this will make dealing with it in other bundles more convenient
@markus-moser

move DefaultAbstractUserawareCustomer functionality to trait

---

src/CustomerSaveManager/DefaultCustomerSaveManager.php

the duplicate-check should only be executed if the customer is active. field-validation should not be skipped though since this may lead to problems setting an inactive customer active

skip duplicates check if the customer is inactive

---

src/CustomerSaveValidator/DefaultCustomerSaveValidator.php

a better way to skip duplicate checks as merged in https://github.com/pimcore/customer-data-framework/pull/61 would be this way. due to the check of isPublished on preAdd and not on preUpdate on the old PR it may be inconsistent
if you favor this PR just revert the last commit with https://github.com/pimcore/customer-data-framework/pull/62 and merge this PR
@fashxp @markus-moser

only validate Duplicates if the customer is published and active

---

src/SegmentManager/SegmentBuilderExecutor/DefaultSegmentBuilderExecutor.php

I was wondering why the segment builder always started at the last page. Turns out that there was a value hardcoded in `DefaultSegmentBuilderExecutor`, so that the wrong option was returned for all calls to `getIntOption`.
I've replaced the hardcoded value with the `$option` parameter that was already present in the function.

Return correct option value in DefaultSegmentBuilderExecutor

---

src/CustomerProvider/CustomerProviderInterface.php
src/CustomerProvider/DefaultCustomerProvider.php
src/DuplicatesIndex/DefaultMariaDbDuplicatesIndex.php
src/Security/UserProvider/CustomerObjectUserProvider.php

Adds a method 'setActiveCondition' to the DefaultCustomerProvider. 
This method can be easily overwritten when you want to use a different field for the 'active' flag.

refactore active condition for the customerlist

---

src/Newsletter/Queue/DefaultNewsletterQueue.php

Avoid running too many newsletter queue sync scripts in parallel, in particular when many records are processed from the CLI.

Avoid running too many scripts in parallel

---

README.md
composer.json
src/Resources/public/css/pimcore.css
src/Resources/public/js/SegmentAddressSource.js
src/Resources/public/js/SegmentAssignmentView.js

With Pimcore 5.4 the location of static Pimcore files like icons has changed. In order to make this bundle work with Pimcore < 5.4, please add following rewrite rule to your `.htaccess`.
```
RewriteRule ^bundles/pimcoreadmin/(.*) /pimcore/static6/$1 [PT,L]
```

updated for pimcore 5.4

---

src/Traits/ApplicationLoggerAware.php

When running `bin/console cmf:newsletter-sync --enqueue-all-customers -c` I was getting the error:
`Argument 1 passed to Pimcore\Log\Handler\ApplicationLoggerDb::__construct() must be an instance of Pimcore\Db\Connection, string given, called in /var/www/html/vendor/pimcore/customer-management-framework-bundle/src/Traits/ApplicationLoggerAware.php on line 44`
It looks like the referenced file is running a check against the Pimcore build number, which was deprecated in 5.4.0. The logic is failing and as such, the `ApplicationLoggerDb` class is not being instantiated correctly.
The offending code on lines 43 to 47 is:
```
if(\Pimcore\Version::getRevision() < 143) {
$dbWriter = new ApplicationLoggerDb('notice');
} else {
$dbWriter = new ApplicationLoggerDb(Db::get(),'notice');
}
```
If …

Fix ApplicationLoggerDb() instantiation

---

src/Listing/Filter/Permission.php

In the user permission filter for the customer listing, if the workspace is the root workspace  `/` the condition will be `LIKE '//%'`, which then results in a  no-results list.

Wrong list permission filter for root workspace

---

src/CustomerDuplicatesService/DefaultCustomerDuplicatesService.php

escape the underscore so that it is interpreted as underscore and not as wildcard

[CUSTOMER][DUPLICATESSERVICE] escape '_'

---

src/Controller/Admin/ActivitiesController.php

Currently filtering in admin panel (customer perspective) is not working. This fix allows admin to filter customer activities based on their type.

Fix admin panel filtering

---

src/Listing/Filter/AbstractFilter.php
src/Security/SsoIdentity/DefaultSsoIdentityService.php

As of build 270, Pimcore allows for non-int class ids (see https://github.com/pimcore/pimcore/issues/2916). This commit fixes a couple places where the class id was (unnecessarily) cast to an int.

Allow non-int class ids

---

composer.json
doc/18_Single_Sign_On.md

fixes depencendy problems with `hwi/oauth-bundle` and `php-http/guzzle6-adapter`. 
now project has to decide, which versions of `hwi/oauth-bundle` and dependencies it should install, since this is only and optional module anyway. 
Command to add dependencies (also noted in docs): `composer require hwi/oauth-bundle php-http/guzzle6-adapter:^1 php-http/httplug-bundle`
fixes #119

Dependency fix

---

src/CustomerProvider/DefaultCustomerProvider.php
src/CustomerProvider/Exception/DuplicateCustomersFoundException.php
src/Newsletter/ProviderHandler/Mailchimp.php
src/Newsletter/ProviderHandler/Mailchimp/CliSyncProcessor.php
src/Newsletter/ProviderHandler/Mailchimp/WebhookProcessor.php

This makes it possible to extend the logic for finding a customer by email address project and newsletter list specific.

[Mailchimp Sync] Delegate getActiveCustomerByEmail() to mailchimp newsletter handler and improve error handling

---

src/SegmentAssignment/SegmentAssigner/SegmentAssigner.php

For some database configurations it is not possible to execute multiple queries at once.
Thus, this PR updated the `SegmentAssigner` class to execute the queries separately - which works for every DB.

SegmentAssigner Query Execution

---

src/CustomReport/Adapter/TermSegmentBuilder.php
src/Resources/config/services.yml

```
Deprecation Notice: Class CustomerManagementFrameworkBundle\Adapter\TermSegmentBuilder located in ./vendor/pimcore/customer-management-framework-bundle/src/CustomReport/Adapter/TermSegmentBuilder.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///usr/local/bin/composer/src/Composer/Autoload/ClassMapGenerator.php:185
```

Fix custom report adapter namespace as per psr-4 autoloading standards

---

src/View/Formatter/DefaultViewFormatter.php

The consent values are shown with classnames not as checkboxes, provided in this screenshot
This implements the check to show checkboxes, fix applied shown below

Display the consent values as checkbox not as their class names.

---

composer.json

As the package "mtdowling/cron-expression" is only used [here](https://github.com/pimcore/customer-data-framework/blob/master/src/ActionTrigger/Event/Cron.php#L36) and the PHP API isn't any different in "dragonmantank/cron-expression", we can simply replace the composer require statement.
This also removes the many warnings in the console when using composer:
```log
Warning: Ambiguous class resolution, "Cron\FieldFactory" was found 2x: in "/var/www/html/vendor/dragonmantank/cron-expression/src/Cron/FieldFactory.php" and "/var/www/html/vendor/mtdowling/cron-expression/src/Cron/FieldFactory.php", the first will be used.
Warning: Ambiguous class resolution, "Cron\DayOfMonthField" was found 2x: in "/var/www/html/vendor/dragonmantank/cron-expression/src/Cron/DayOfMonthField.php" and …
```

Replace "mtdowling/cron-expression"

---

src/Targeting/ActionHandler/ApplyTargetGroupsFromSegments.php

In case the given target group is not found, the `clearAssignedTargetGroup` would fail with en error. Therefore simple test for target group presence.

clearAssignedTargetGroup null target group fix

---

src/SegmentAssignment/QueueBuilder/DefaultQueueBuilder.php

the asset table does not have a "key" row. It uses "filename"

fixed enqueue children for type asset

---

doc/03_Configuration.md
src/Newsletter/ProviderHandler/Mailchimp.php
src/Newsletter/ProviderHandler/Mailchimp/DataTransformer/Address.php

Currently only "simple" Mailchimp merge-fields are supported.
However, Mailchimp has the complex "field-type" ADDRESS which accepts properties as defined here: https://us1.api.mailchimp.com/schema/3.0/Lists/Members/MergeField.json
The changes made allow to stitch data from multiple fields together into a single merge field.
Further the changes provide a data transformer that allows to set the properties of the ADDRESS field by mapping the proper service name. It also provides a way to add a dummy `state` property as this isn't used in all countries but is a required property.
This might be an API change as it changes the behavior in case someone sets a merge field multiple types with a value of the type array.
Other than that the changes should be fully backward compatible with existing …

Added support for Mailchimps multi-value merge-field ADDRESS.

---

src/Resources/views/admin/customers/partials/list_filter/user_roles.html.twig

The loop variable has been named wrong because in the loop body role will be used (instead of user)

Changed variable name for Twig function
